### ISSUE TITLE
导航栏图标加载错误，设置界面图标正常

### ISSUE THREAD

**Issue by sandwichii** [xyh20180101/RomajiConverter.WinUI#3]
![Snipaste_2023-12-04_13-59-49](https://github.com/xyh20180101/RomajiConverter.WinUI/assets/8279800/2ae7d7ad-d34b-46ed-81ad-982c51c72415)

![Snipaste_2023-12-04_14-01-14](https://github.com/xyh20180101/RomajiConverter.WinUI/assets/8279800/043c8f86-87f5-4dbe-b8db-a948079908e9)

**Comment by xyh20180101** [comment]
可能是系统字体的原因，我这不好复现，不过试着根据这个改了[https://github.com/microsoft/microsoft-ui-xaml/issues/6392](https://github.com/microsoft/microsoft-ui-xaml/issues/6392)
你看下最新版还有没有这个问题[https://github.com/xyh20180101/RomajiConverter.WinUI/releases/tag/1.1.1](https://github.com/xyh20180101/RomajiConverter.WinUI/releases/tag/1.1.1)

**Comment by sandwichii** [comment]
> 可能是系统字体的原因，我这不好复现，不过试着根据这个改了[microsoft/microsoft-ui-xaml#6392](https://github.com/microsoft/microsoft-ui-xaml/issues/6392) 你看下最新版还有没有这个问题https://github.com/xyh20180101/RomajiConverter.WinUI/releases/tag/1.1.1

没问题了
