### ISSUE TITLE
对于类似“フェ”的外来语罗马音展示优化

### ISSUE THREAD

**Issue by baka719** [xyh20180101/RomajiConverter.WinUI#5]
![QQ截图20231226014748](https://github.com/xyh20180101/RomajiConverter.WinUI/assets/20205827/9cfa049f-cc33-4069-a06d-c2e8a7356f15)
对于 ```フェ``` 音，可能相对于 ```fue``` 的写法，更常用的写法是 ```fe``` 。

**Comment by baka719** [comment]
![image](https://github.com/xyh20180101/RomajiConverter.WinUI/assets/20205827/013c69d7-f489-4633-afa2-a27ce4f69a89)
这里的 ```ファ``` ```ティ``` 情况类似，相对于 ```fua``` ```tei``` 更常写作 ```fa``` ```ti```

**Comment by xyh20180101** [comment]
修了，[https://github.com/xyh20180101/RomajiConverter.WinUI/releases/tag/1.2.0](https://github.com/xyh20180101/RomajiConverter.WinUI/releases/tag/1.2.0) 看看
