### ISSUE TITLE
部分歌曲无法【获取网易云歌词】

### ISSUE THREAD

**Issue by y25552** [xyh20180101/RomajiConverter.WinUI#7]
例如
人マニア
散り散り
点击【获取网易云歌词】后直接清空，不显示任何内容

**Comment by xyh20180101** [comment]
已修复。原因：无法解析部分歌曲的lrc歌词
[https://github.com/xyh20180101/RomajiConverter.WinUI/releases/tag/1.2.1](https://github.com/xyh20180101/RomajiConverter.WinUI/releases/tag/1.2.1)
