### ISSUE TITLE
Index was outside the bounds of the array.索引超出了数组的边界。

### ISSUE THREAD

**Issue by y25552** [xyh20180101/RomajiConverter.WinUI#8]
ウルトラトレーラー
在进行转换时出现该问题
![罗马音转换器 2024_2_1 10_06_01](https://github.com/xyh20180101/RomajiConverter.WinUI/assets/55015490/f96bac2d-afab-4993-a9ee-d9b8f0e4558f)

**Comment by xyh20180101** [comment]
已修复。原因：日文判断和假名转换逻辑有问题
[https://github.com/xyh20180101/RomajiConverter.WinUI/releases/tag/1.2.1](https://github.com/xyh20180101/RomajiConverter.WinUI/releases/tag/1.2.1)
